# Usage:
#   Rscript "01.Olink bridging normalization.R"
#   Rscript "01.Olink bridging normalization.R" --batch1 batch1.xlsx --batch2 batch2.xlsx --outdir results

library(OlinkAnalyze)
library(dplyr)
library(ggplot2)
library(stringr)

parse_cli_value <- function(args, flags) {
  idx <- match(flags, args)
  idx <- idx[!is.na(idx)][1]
  if (is.na(idx)) {
    return(NULL)
  }
  if (idx == length(args)) {
    stop(sprintf("Missing value after %s", args[[idx]]))
  }
  args[[idx + 1]]
}

read_npx_checked <- function(path, label) {
  if (!file.exists(path)) {
    stop(sprintf("%s file not found: %s", label, path))
  }
  tryCatch(
    read_NPX(path),
    error = function(e) {
      stop(sprintf("%s could not be read by OlinkAnalyze::read_NPX(): %s", label, e$message))
    }
  )
}

resolve_sample_id_column <- function(df, label) {
  candidates <- c("SampleID", "Sample Id", "Sample_ID", "sampleID", "sample_id")
  matched <- candidates[candidates %in% names(df)]
  if (length(matched) == 0) {
    stop(sprintf(
      "%s is missing a recognizable sample ID column. Expected one of: %s",
      label, paste(candidates, collapse = ", ")
    ))
  }
  matched[[1]]
}

check_required_columns <- function(df, label, sample_col) {
  required_cols <- c("NPX", "Panel", "Assay", sample_col)
  missing_cols <- setdiff(required_cols, names(df))
  if (length(missing_cols) > 0) {
    stop(sprintf(
      "%s is missing required columns: %s",
      label, paste(missing_cols, collapse = ", ")
    ))
  }
}

args <- commandArgs(trailingOnly = TRUE)
batch1_path <- parse_cli_value(args, c("--batch1", "-a"))
batch2_path <- parse_cli_value(args, c("--batch2", "-b"))
outdir <- parse_cli_value(args, c("--outdir", "-o"))

if (is.null(outdir) || !nzchar(outdir)) {
  outdir <- "."
}
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

# Import batches of NPX data generated by Olink NPX Signature
if (is.null(batch1_path) || !nzchar(batch1_path)) {
  batch1_path <- file.choose()
}
if (is.null(batch2_path) || !nzchar(batch2_path)) {
  batch2_path <- file.choose()
}

data1 <- read_npx_checked(batch1_path, "Batch 1")
data2 <- read_npx_checked(batch2_path, "Batch 2")

sample_col1 <- resolve_sample_id_column(data1, "Batch 1")
sample_col2 <- resolve_sample_id_column(data2, "Batch 2")
check_required_columns(data1, "Batch 1", sample_col1)
check_required_columns(data2, "Batch 2", sample_col2)

# Merge different batches of data
npx1 <- data1 %>%
  mutate(dataset = "data1")

npx2 <- data2 %>%
  mutate(dataset = "data2")

npx_df <- bind_rows(npx1, npx2)

# Set bridging samples
overlap_samples <- c(
  "PAR202207197", "PAR202208265", "PAR202204023", "PAR202204027",
  "PAR202208275", "PAR202204021", "PAR202204019", "PAR202205059"
)

missing_batch1 <- setdiff(overlap_samples, unique(as.character(npx1[[sample_col1]])))
missing_batch2 <- setdiff(overlap_samples, unique(as.character(npx2[[sample_col2]])))

if (length(missing_batch1) == length(overlap_samples) || length(missing_batch2) == length(overlap_samples)) {
  stop(
    paste0(
      "None of the configured overlap_samples were found in at least one batch. ",
      "Please confirm the sample ID column and file contents."
    )
  )
}

if (length(missing_batch1) > 0 || length(missing_batch2) > 0) {
  warning(
    paste0(
      "Some overlap_samples are missing. Batch 1 missing: ",
      if (length(missing_batch1) == 0) "none" else paste(missing_batch1, collapse = ", "),
      ". Batch 2 missing: ",
      if (length(missing_batch2) == 0) "none" else paste(missing_batch2, collapse = ", "),
      "."
    )
  )
}

# Before normalization evaluation
before_plot <- npx_df %>%
  mutate(Panel = gsub("Olink", "", Panel)) %>%
  ggplot(aes(x = NPX, fill = dataset)) +
  geom_density(alpha = 0.4) +
  facet_grid(~Panel) +
  set_plot_theme() +
  ggtitle("Before bridging normalization: NPX distribution") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.text = element_text(size = 16),
    legend.title = element_blank(),
    legend.position = "top"
  )

ggsave(
  filename = file.path(outdir, "Olink_density_before_normalization.pdf"),
  plot = before_plot,
  width = 10,
  height = 6
)

# Bridging normalization
npx_br_data <- olink_normalization(
  df1 = npx1,
  df2 = npx2,
  overlapping_samples_df1 = overlap_samples,
  df1_project_nr = "data1",
  df2_project_nr = "data2",
  reference_project = "data1"
)

# Evaluation after normalization
after_plot <- npx_br_data %>%
  mutate(Panel = gsub("Olink", "", Panel)) %>%
  ggplot(aes(x = NPX, fill = dataset)) +
  geom_density(alpha = 0.4) +
  facet_grid(~Panel) +
  set_plot_theme() +
  ggtitle("After bridging normalization: NPX distribution") +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.text = element_text(size = 16),
    legend.title = element_blank(),
    legend.position = "top"
  )

ggsave(
  filename = file.path(outdir, "Olink_density_after_normalization.pdf"),
  plot = after_plot,
  width = 10,
  height = 6
)

# Export bridging normalized data
write.csv(npx_br_data, file = file.path(outdir, "Bridge_Normalized_NPX_data.csv"), row.names = FALSE)
